import type { Property } from "../lib/type";

export const properties: Property[] = [
	{
		id: 1,
		status: "Premium",
		desc: "Sophisticated penthouse with contemporary design and premium amenities",
		name: "ABIKE PENTHOUSE",
		location: "Ikoyi, Lagos",
		amenities: [
			"Ocean view",
			"Premium seating",
			"Modern entertainment",
			"Luxury finishes",
		],
		bed: 4,
		baths: 5,
		roomStatus: "AVAILABLE",
		price: 120000,
		images: [
			"/apartment-images/IMG_5673.JPG",
			"/apartment-images/IMG_5674.JPG",
			"/apartment-images/IMG_5675.JPG",
			"/apartment-images/IMG_5676.JPG",
			"/apartment-images/IMG_5677.JPG",
			"/apartment-images/IMG_5678.JPG",
		],
		isSuperhost: true,
		guests: 10,
		isNew: true,
		type: "Short Let",
		rating: 5.0,
		reviews: 89,
	},

	{
		id: 2,
		name: "WHITE-STONE",
		type: "Short Let",
		location: "Victoria Island, Lagos",
		desc: "Elegant luxury apartment with modern curved seating and premium finishes",
		amenities: [
			"Premium furnishing",
			"Smart TV",
			"Modern lighting",
			"Spacious living area",
		],
		price: 85000,
		rating: 4.9,
		reviews: 127,
		images: [
			"/apartment-images/IMG_5267.JPG",
			"/apartment-images/IMG_5268.JPG",
			"/apartment-images/IMG_5269.JPG",
			"/apartment-images/IMG_5259.JPG",
			"/apartment-images/IMG_5265.JPG",
		
		],
		isNew: true,
		bed: 4,
		baths: 2,
		status: "Premium",
		roomStatus: "AVAILABLE",
		guests: 7,
	},

	{
		id: 3,
		name: "OBUDU VILLA",
		type: "Short Let",
		location: "Lekki Phase 1, Lagos",
		desc: "Spacious villa with elegant living spaces and modern comfort",
		amenities: [
			"Spacious layout",
			"Premium furniture",
			"Entertainment center",
			"Luxury amenities",
		],
		price: 95000,
		rating: 4.8,
		reviews: 156,
		images: [
			"/apartment-images/IMG_5699.JPG",
			"/apartment-images/IMG_5701.JPG",
			"/apartment-images/IMG_5703.JPG",
			"/apartment-images/IMG_5704.JPG",
			"/apartment-images/IMG_5705.JPG",
			"/apartment-images/IMG_5708.JPG",
			"/apartment-images/IMG_5709.JPG",
		],
		bed: 3,
		baths: 3,
		guests: 6,
		roomStatus: "LIMITED",
	},

	{
		id: 4,
		name: "ZIRCON",
		type: "Short Let",
		location: "Banana Island, Lagos",
		desc: "Premium apartment with sophisticated design and luxury comfort",
		amenities: [
			"Designer furniture",
			"Modern lighting",
			"Premium finishes",
			"Elegant decor",
		],
		price: 110000,
		rating: 4.9,
		reviews: 203,
		images: [
			"/apartment-images/IMG_5248.JPG",
			"/apartment-images/IMG_5249.JPG",
			"/apartment-images/IMG_5250.JPG",
			"/apartment-images/IMG_5251.JPG",
			"/apartment-images/IMG_5252.JPG",
			"/apartment-images/IMG_5253.JPG",
			"/apartment-images/IMG_5254.JPG",
		],
		bed: 4,
		baths: 5,
		guests: 10,
		roomStatus: "AVAILABLE",
	},
];
