import type { Property } from "@lib/type";

export const properties: Property[] = [
	{
		id: "cmgz4kxpt002een4t130q8w45",
		status: "Premium",
		desc: `Nestled within the prestigious Abike Residence, the Abike Penthouse is a stunning 2-bedroom luxury suite that reflects the very essence of Mar Abu${"'"}s commitment to excellence. Built by us, owned by us.Designed for those who appreciate refined living, this fully furnished penthouse offers a seamless blend of modern comfort, sophisticated aesthetics, and unmatched build quality.`,
		name: "ABIKE PENTHOUSE",
		location: "Oribanwa phase II, ibeju-Lekki",
		amenities: [
			"Curated Interiors",
			"Equipped Kitchen",
			"Sleek Bathrooms",
			"Natural Light",
			"Private Access",
		],
		bed: 2,
		baths: 2,
		roomStatus: "AVAILABLE",
		price: 200000,
		images: [
			"/apartment-images/abike-penthouse/IMG_5289.jpeg",
			"/apartment-images/abike-penthouse/IMG_5280.jpeg",
			"/apartment-images/abike-penthouse/IMG_5276.jpeg",
			"/apartment-images/abike-penthouse/IMG_5275.jpeg",
			"/apartment-images/abike-penthouse/IMG_5273.jpeg",
			"/apartment-images/abike-penthouse/IMG_5281.jpeg",
			"/apartment-images/abike-penthouse/IMG_5282.jpeg",
			"/apartment-images/abike-penthouse/IMG_5283.jpeg",
			"/apartment-images/abike-penthouse/IMG_5285.jpeg",
			"/apartment-images/abike-penthouse/IMG_5287.jpeg",
			"/apartment-images/abike-penthouse/IMG_5288.jpeg",
			"/apartment-images/abike-penthouse/IMG_5291.jpeg",
			"/apartment-images/abike-penthouse/IMG_5673.jpeg",
			"/apartment-images/abike-penthouse/IMG_5272.jpeg",
		],
		isSuperhost: true,
		guests: 10,
		isNew: true,
		type: "Short Let",
		rating: 5.0,
		reviews: 89,
		specials: [
			"2 Spacious Bedrooms &ndash; Contemporary finishes for comfort and style.",
			"Tastefully Curated Interiors &ndash; Premium furniture and décor for a luxurious feel.",
			"Fully Equipped Kitchen &ndash; Modern appliances for convenient cooking.",
			"Sleek Bathrooms &ndash; Fitted with top-grade sanitary wares.",
			"Elegant Lighting &ndash; Natural light and ambient lighting create a welcoming atmosphere.",
			"Private Top-Floor Access &ndash; Enjoy serene views and exclusive privacy.",
		],
	},

	{
		id: "cmgz4kxpn001qen4thm3opn2r",
		name: "WHITE-STONE",
		type: "Short Let",
		location: "Whitestone by Schlepp, Perchstone & Graeys Close, Lekki",
		desc: "Prime location: Whitestone by Schlepp, Perchstone & Graeys Close, Lekki. This is where luxury, smart living, and minimalist elegance meet. Located in the heart of Lekki, this ultra-spacious 2-bedroom shortlet is designed for those who crave comfort, luxury with sophistication.",
		amenities: [
			"Outer lounge area",
			"Dining area",
			"Washing machine",
			"Refrigerator",
			"Microwave",
			"Oven",
			"Swimming pool",
			"Balcony with city view",
		],
		price: 350000,
		rating: 4.9,
		reviews: 127,
		images: [
			"/apartment-images/whitestone/IMG_0523.JPG",
			"/apartment-images/whitestone/IMG_0513.JPG",
			"/apartment-images/whitestone/IMG_0507.JPG",
			"/apartment-images/whitestone/IMG_0508.JPG",
			"/apartment-images/whitestone/IMG_0517.JPG",
			"/apartment-images/whitestone/IMG_0518.JPG",
			"/apartment-images/whitestone/IMG_0514.JPG",
			"/apartment-images/whitestone/IMG_0515.JPG",
			"/apartment-images/whitestone/IMG_0510.JPG",
			"/apartment-images/whitestone/IMG_0520.JPG",
			"/apartment-images/whitestone/IMG_0521.JPG",
			"/apartment-images/whitestone/IMG_0522.JPG",
			"/apartment-images/whitestone/IMG_0509.JPG",
			"/apartment-images/whitestone/IMG_0516.JPG",
		],
		isNew: true,
		bed: 2,
		baths: 2,
		status: "Premium",
		roomStatus: "AVAILABLE",
		guests: 7,
		specials: [
			"Unwind in the stylish outer lounge area &ndash; perfect for relaxing or entertaining",
			"Dine in comfort &ndash; spacious dining area for shared meals and special moments",
			"Enjoy the convenience of a washing machine &ndash; travel light and stay fresh",
			"Keep your groceries fresh with a full-sized refrigerator",
			"Heat and cook with ease &ndash; equipped with a microwave and oven",
			"Make a splash anytime &ndash; access to a beautiful swimming pool",
			"Start or end your day with a view &ndash; balcony overlooking the city skyline"
		],
		minimumNights: 3,
	},

	{
		id: "cmhi80phg0007fk4u73pxj2gt",
		name: "OBUDU VILLA 8",
		type: "Short Let",
		location: "lakowe lakes golf & country estate, ibeju-lekki",
		desc: "Escape to Obudu Villa, a luxurious 2 bedroom apartment tucked within Lakowe Lakes Golf & Country Estate—a grand 308-hectare sanctuary dubbed West Africa’s best-kept secret  . This exceptional estate blends breathtaking nature with upscale leisure: an 18-hole championship golf course, over 14 serene lakes, lush palm groves, and resort-style recreation.",
		amenities: [
			"Washing machine",
			"Refrigerator",
			"Oven",
			"Microwave",
			"Alexa voice control",
			"Work space",
			"Free parking",
			"Dining area",
			"Balcony with a view",
			"Swimming pool access for two",
		],
		price: 380000,
		rating: 4.8,
		reviews: 156,
		images: [
			"/apartment-images/obudu/IMG_5301.jpeg",
			"/apartment-images/obudu/IMG_5303.jpeg",
			"/apartment-images/obudu/IMG_5456.jpeg",
			"/apartment-images/obudu/IMG_5694.jpeg",
			"/apartment-images/obudu/IMG_5698.jpeg",
			"/apartment-images/obudu/IMG_5700.jpeg",
			"/apartment-images/obudu/IMG_5708.jpeg",
			"/apartment-images/obudu/IMG_5709.jpeg",
			"/apartment-images/obudu/IMG_3652.jpeg",
			"/apartment-images/obudu/IMG_3647.jpeg",
		],
		bed: 2,
		baths: 2,
		guests: 6,
		roomStatus: "LIMITED",
		specials: [
			"Enjoy the convenience of a fully equipped kitchen with oven, microwave, and refrigerator",
			"Stay fresh and travel light with your own in-unit washing machine",
			"Control your space hands-free with Alexa voice control throughout the home",
			"Perfect for remote work &ndash; includes a dedicated workspace with reliable comfort",
			"Take in beautiful views from your private balcony",
			"Relax with complimentary swimming pool access for two guests",
			"Dine comfortably in a stylish and spacious dining area",
			"Hassle-free travel with free on-site parking available",
		],
	},

	{
		id: "cmgz4kxph000uen4t8kq9i83r",
		name: "ZIRCON",
		type: "Short Let",
		location: "sapphire garden estate, awoyaya, ibeju lekki",
		desc: `Located on Zircon Road, Sapphire Garden Estate, in the heart of Awoyaya, Ibeju-Lekki, Zircon is a beautifully designed 4-Bedroom Semi-Detached Duplex tailored for comfort, leisure, and connection. Whether it${"'"}s a cozy family weekend, a lively hangout with friends, or an intimate private party, Zircon gives you the perfect setting. With its spacious interiors, modern finishing, and warm, homely atmosphere, it combines both comfort and functionality.`,
		amenities: [
			"Microwave",
			"Oven",
			"Washing machine",
			"Refrigerator",
			"Bathtub (master bathroom)",
			"Game area ( pool and table tennis)",
			"WiFi",
			"PS5",
			"Netflix and dstv",
			"Aquarium",
			"Dining area",
		],
		price: 160000,
		rating: 4.9,
		reviews: 203,
		images: [
			"/apartment-images/zircon/IMG_4790.JPG",
			"/apartment-images/zircon/IMG_4793.JPG",
			"/apartment-images/zircon/IMG_4795.JPG",
			"/apartment-images/zircon/IMG_4798.JPG",
			"/apartment-images/zircon/IMG_4799.JPG",
			"/apartment-images/zircon/IMG_5248.jpeg",
			"/apartment-images/zircon/IMG_5252.jpeg",
			"/apartment-images/zircon/IMG_5254.jpeg",
			"/apartment-images/zircon/IMG_5255.jpeg",
			"/apartment-images/zircon/IMG_5256.jpeg",
			"/apartment-images/zircon/IMG_5257.jpeg",
			"/apartment-images/zircon/IMG_5259.jpeg",
			"/apartment-images/zircon/IMG_5263.jpeg",
			"/apartment-images/zircon/IMG_5267.jpeg",
			"/apartment-images/zircon/IMG_5268.jpeg",
		],
		bed: 4,
		baths: 4,
		guests: 10,
		roomStatus: "AVAILABLE",
		specials: [
			"Unwind with high-speed WiFi and complimentary access to Netflix & DStv",
			"Enjoy endless fun in the dedicated game area with pool and table tennis",
			"Experience next-level entertainment with a PS5 gaming console",
			"Relax in the luxurious master bathroom featuring a private bathtub",
			"Cook like home with a fully equipped kitchen &ndash; oven, microwave, and refrigerator included",
			"Stay fresh with an in-unit washing machine",
			"Explore the underwater world from the comfort of your stay &ndash; on-site aquarium included",
			"Dine in style with a spacious and elegant dining area",
		],
	},

	{
		id: "cmhi80phw0011fk4uc5ghteny",
		name: "OBUDU VILLA 10",
		type: "Short Let",
		location: "lakowe lakes golf & country estate, ibeju-lekki",
		desc: "Escape to Obudu Villa, a luxurious 2 bedroom apartment tucked within Lakowe Lakes Golf & Country Estate—a grand 308-hectare sanctuary dubbed West Africa’s best-kept secret  . This exceptional estate blends breathtaking nature with upscale leisure: an 18-hole championship golf course, over 14 serene lakes, lush palm groves, and resort-style recreation.",
		amenities: [
			"Washing machine",
			"Refrigerator",
			"Oven",
			"Microwave",
			"Alexa voice control",
			"Work space",
			"Free parking",
			"Dining area",
			"Balcony with a view",
			"Swimming pool access for two",
		],
		price: 380000,
		rating: 4.8,
		reviews: 156,
		images: [
			"/apartment-images/obudu/IMG_5301.jpeg",
			"/apartment-images/obudu/IMG_5303.jpeg",
			"/apartment-images/obudu/IMG_5456.jpeg",
			"/apartment-images/obudu/IMG_5694.jpeg",
			"/apartment-images/obudu/IMG_5698.jpeg",
			"/apartment-images/obudu/IMG_5700.jpeg",
			"/apartment-images/obudu/IMG_5708.jpeg",
			"/apartment-images/obudu/IMG_5709.jpeg",
			"/apartment-images/obudu/IMG_3652.jpeg",
			"/apartment-images/obudu/IMG_3647.jpeg",
		],
		bed: 2,
		baths: 2,
		guests: 6,
		roomStatus: "LIMITED",
		specials: [
			"Enjoy the convenience of a fully equipped kitchen with oven, microwave, and refrigerator",
			"Stay fresh and travel light with your own in-unit washing machine",
			"Control your space hands-free with Alexa voice control throughout the home",
			"Perfect for remote work &ndash; includes a dedicated workspace with reliable comfort",
			"Take in beautiful views from your private balcony",
			"Relax with complimentary swimming pool access for two guests",
			"Dine comfortably in a stylish and spacious dining area",
			"Hassle-free travel with free on-site parking available",
		],
	},
];
